### ISSUE TITLE
get rid of confd in cnt

### ISSUE THREAD

**Issue by slallema** [blablacar/cnt#70]
since we're only using confd for templating and extend templating capabilities for our needs.

**Comment by nyodas** [comment]
Include a folder to have some go template ready.
To be able to call them in the other template.
cf [Godoc](https://golang.org/pkg/text/template/)

```go
`{{define "T1"}}ONE{{end}}
{{define "T2"}}TWO{{end}}
{{define "T3"}}{{template "T1"}} {{template "T2"}}{{end}}
{{template "T3"}}`
```

**Comment by nyodas** [comment]
Add a function to define a default value. 
to avoid having a line like 
`{{if lol}} {{lol}} {{else}}pom {{end}}`

could look like
`{{default lol pom}}`

That would make a lot of templates a lot cleaner.

Not sure of the usefulness of the next one but just in case. 
currently the `{{range}}` output an empty line when the array is empty or the value ain't there. 
Could we have thw possibility to add a default member when that happens?

**Comment by n0rad** [comment]
support include of template in other templates

**Comment by n0rad** [comment]
done
