### ISSUE TITLE
cnt play

### ISSUE THREAD

**Issue by nyodas** [blablacar/cnt#96]
Could we have a command that 

```
cnt update
rkt run # with DEBUG/TRACE level to see the resolving template.
```
This is for a quick iteration process.

The need for this is to resolve/compile the template and output them.

**Comment by n0rad** [comment]
not sure it's a good approch. especially since I don't know what should be the rkt parameters.

`cnt update && rkt run --set-env=LOG_LEVEL=TRACE ...` should do the job ?

**Comment by n0rad** [comment]
use `cnt update && rkt run --set-env=LOG_LEVEL=TRACE ...` instead
